# Generated by Django 4.0.4 on 2022-05-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
