# Generated by Django 4.0.4 on 2022-06-06 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_jobpost_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostactivity',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobpost'),
        ),
    ]
