# Generated by Django 4.0.4 on 2022-04-25 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seekerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1),
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_degree_name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=50)),
                ('institute_university_name', models.CharField(max_length=50)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('complete_year', models.PositiveSmallIntegerField()),
                ('grading_system', models.CharField(max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
