# Generated by Django 4.0.4 on 2022-04-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_seekerprofile_gender_educationdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationdetail',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='grading_system',
        ),
    ]
