# Generated by Django 4.0.4 on 2022-04-26 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_certificate_degree_name_educationdetail_certified_degree_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
