# Generated by Django 4.0.4 on 2022-04-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_educationdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='complete_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='start_year',
            field=models.PositiveIntegerField(),
        ),
    ]
